# 课堂练习：Pandas 数据处理与分析
**课程**：数据可视化  
**学号**：17420249605674  
**姓名**：沈美梓  
**课件出处**：Ch3 Python可视化库 p.27  

---

### 练习要求：
根据提供的数据集：`customers.txt`
1. 读取数据到 DataFrame 中
2. 查看数据集中各个属性（列）的类型
3. 打印前五行和后五行的数据
4. 查看属性 education、occupation、income 的可能取值有哪些
5. 选择出客户 ID 为 "Cust-21910" 的行
6. 将 marital 字段重新赋值：是改为 1，否改为 0
7. 将数据拆分为男性客户和女性客户两个样本
8. 依次输出男性客户中，高价值客户、中等价值客户、低价值客户的教育水平的众数、已婚人数比例，以及年龄的均值
9. 将女性客户样本导出到 Excel 中

In [1]:
import pandas as pd
import numpy as np

# 设置 pandas 显示选项，便于查看完整表格
pd.set_option('display.max_columns', 20)
pd.set_option('display.width', 1000)

### 1) 读取数据到 DataFrame 中

In [2]:
# 1) 读取 customers.txt 数据集
df = pd.read_csv('customers.txt')
print("数据集总维度 (行数, 列数)：", df.shape)
df.head()

数据集总维度 (行数, 列数)： (790, 12)

      cust_id gender  age education occupation  income    telephone marital                         email              address retire custcat
0  Cust-10015      男   34        高中       普通工人   5至10万  151****0139       是  jaclyn12@adventure-works.com  3448 Sun View Terr.      否   高价值客户
1  Cust-10030      男   54    硕士及其以上       技术工人  10至20万  132****0174       是   mariah6@adventure-works.com        4924 Mariposa      否   低价值客户
2  Cust-10045      男   37        高中       普通工人   5至10万  185****0117       否    ebony4@adventure-works.com        4381 Amazonas      否   低价值客户
3  Cust-10060      女   60    初中及其以下       普通工人    5万以下  155****0164       是   brooke7@adventure-works.com           5720 A St.      是   低价值客户
4  Cust-10075      男   28        本科       公司白领   30万以上  145****0190       是  dalton18@adventure-works.com  1906 Seaview Avenue      否  一般价值客户

### 2) 查看数据集中各个属性（列）的类型

In [3]:
# 2) 查看数据集中各个属性（列）的数据类型
print("各属性数据类型：")
print(df.dtypes)

各属性数据类型：
cust_id       object
gender        object
age            int64
education     object
occupation    object
income        object
telephone     object
marital       object
email         object
address       object
retire        object
custcat       object
dtype: object

### 3) 打印前五行和后五行的数据

In [4]:
# 3) 打印前五行和后五行的数据
print("====== 前五行数据 (head) ======")
display(df.head(5))

print("\n====== 后五行数据 (tail) ======")
display(df.tail(5))

====== 前五行数据 (head) ======

      cust_id gender  age education occupation  income    telephone marital                         email              address retire custcat
0  Cust-10015      男   34        高中       普通工人   5至10万  151****0139       是  jaclyn12@adventure-works.com  3448 Sun View Terr.      否   高价值客户
1  Cust-10030      男   54    硕士及其以上       技术工人  10至20万  132****0174       是   mariah6@adventure-works.com        4924 Mariposa      否   低价值客户
2  Cust-10045      男   37        高中       普通工人   5至10万  185****0117       否    ebony4@adventure-works.com        4381 Amazonas      否   低价值客户
3  Cust-10060      女   60    初中及其以下       普通工人    5万以下  155****0164       是   brooke7@adventure-works.com           5720 A St.      是   低价值客户
4  Cust-10075      男   28        本科       公司白领   30万以上  145****0190       是  dalton18@adventure-works.com  1906 Seaview Avenue      否  一般价值客户

====== 后五行数据 (tail) ======

        cust_id gender  age education occupation income    telephone marital                          email                address retire custcat
785  Cust-21880      女   37        高中       普通工人  5至10万  177****0166       是  bethany10@adventure-works.com  1080 Crestwood Circle      否   高价值客户
786  Cust-21895      男   27        大专       普通工人   5万以下  130****0128       是      abby4@adventure-works.com        7834 Roux Court      否   低价值客户
787  Cust-21910      女   47        本科       管理人员  30万以上  152****0148       是    ariana5@adventure-works.com      3792 Westwood Ct.      否  一般价值客户
788  Cust-21925      男   61        高中       普通工人  5至10万  181****0178       否    lucas10@adventure-works.com      7901 Moccasin Ct.      否   高价值客户
789  Cust-10615      女   63        高中       普通工人  5至10万  185****0168       否  vincent21@adventure-works.com       4059 High Street      是  一般价值客户

### 4) 查看属性 education、occupation、income 的可能取值有哪些

In [5]:
# 4) 查看指定属性的可能取值（唯一值）
target_columns = ['education', 'occupation', 'income']

for col in target_columns:
    unique_vals = df[col].unique()
    print(f"【{col}】的可能取值 ({len(unique_vals)} 种)：")
    print(list(unique_vals))
    print("-" * 60)

【education】的可能取值 (5 种)：
['高中', '硕士及其以上', '初中及其以下', '本科', '大专']
------------------------------------------------------------
【occupation】的可能取值 (5 种)：
['普通工人', '技术工人', '公司白领', '管理人员', '专业人员']
------------------------------------------------------------
【income】的可能取值 (5 种)：
['5至10万', '10至20万', '5万以下', '30万以上', '20至30万']
------------------------------------------------------------

### 5) 选择出客户 ID 为 "Cust-21910" 的行

In [6]:
# 5) 通过布尔索引筛选出客户 ID 为 'Cust-21910' 的行
cust_21910 = df[df['cust_id'] == 'Cust-21910']
cust_21910

        cust_id gender  age education occupation income    telephone marital                        email            address retire custcat
787  Cust-21910      女   47        本科       管理人员  30万以上  152****0148       是  ariana5@adventure-works.com  3792 Westwood Ct.      否  一般价值客户

### 6) 将 marital 字段重新赋值：是改为 1，否改为 0

In [7]:
# 6) 将 marital 字段中的 '是' 映射为 1，'否' 映射为 0
df['marital'] = df['marital'].map({'是': 1, '否': 0})

# 验证赋值结果与分布
print("marital 字段唯一值：", df['marital'].unique())
print("重新赋值后的 marital 频数统计：")
print(df['marital'].value_counts())

marital 字段唯一值： [1 0]
重新赋值后的 marital 频数统计：
marital
0    398
1    392
Name: count, dtype: int64

### 7) 将数据拆分为男性客户和女性客户两个样本

In [8]:
# 7) 按性别 (gender) 拆分样本
male_df = df[df['gender'] == '男'].copy()
female_df = df[df['gender'] == '女'].copy()

print(f"男性客户样本数量：{len(male_df)} 人")
print(f"女性客户样本数量：{len(female_df)} 人")
print(f"总计验证：{len(male_df) + len(female_df)} / {len(df)}")

男性客户样本数量：390 人
女性客户样本数量：400 人
总计验证：790 / 790

### 8) 依次输出男性客户中，高价值客户、中等价值客户、低价值客户的教育水平的众数、已婚人数比例，以及年龄的均值

In [9]:
# 8) 分析男性客户在各价值等级下的特征指标
# 注：数据集中 '一般价值客户' 即对应题目中的 '中等价值客户'
customer_categories = ['高价值客户', '一般价值客户', '低价值客户']

summary_records = []

for cat in customer_categories:
    sub_df = male_df[male_df['custcat'] == cat]
    
    # 1. 教育水平众数
    edu_mode = sub_df['education'].mode()[0]
    # 2. 已婚人数比例 (marital为1的比例，即mean)
    married_ratio = sub_df['marital'].mean()
    # 3. 年龄均值
    age_mean = sub_df['age'].mean()
    
    # 格式化名称便于对应题目
    display_name = '中等价值客户 (一般价值客户)' if cat == '一般价值客户' else cat
    print(f"【{display_name}】(样本数: {len(sub_df)})：")
    print(f"  - 教育水平众数: {edu_mode}")
    print(f"  - 已婚人数比例: {married_ratio:.4f} ({married_ratio*100:.2f}%)")
    print(f"  - 年龄均值:     {age_mean:.2f} 岁")
    print("-" * 50)
    
    summary_records.append({
        '客户分类': display_name,
        '样本人数': len(sub_df),
        '教育水平众数': edu_mode,
        '已婚比例': f"{married_ratio*100:.2f}%",
        '年龄均值': round(age_mean, 2)
    })

# 输出格式化汇总表
summary_df = pd.DataFrame(summary_records)
display(summary_df)

【高价值客户】(样本数: 105)：
  - 教育水平众数: 高中
  - 已婚人数比例: 0.4476 (44.76%)
  - 年龄均值:     41.10 岁
--------------------------------------------------
【中等价值客户 (一般价值客户)】(样本数: 198)：
  - 教育水平众数: 高中
  - 已婚人数比例: 0.5152 (51.52%)
  - 年龄均值:     41.91 岁
--------------------------------------------------
【低价值客户】(样本数: 87)：
  - 教育水平众数: 大专
  - 已婚人数比例: 0.5057 (50.57%)
  - 年龄均值:     42.23 岁
--------------------------------------------------

              客户分类  样本人数 教育水平众数    已婚比例   年龄均值
0            高价值客户   105     高中  44.76%  41.10
1  中等价值客户 (一般价值客户)   198     高中  51.52%  41.91
2            低价值客户    87     大专  50.57%  42.23

### 9) 将女性客户样本导出到 Excel 中

In [10]:
# 9) 将女性客户样本数据导出为 Excel 文件
output_excel = '女性客户样本.xlsx'
female_df.to_excel(output_excel, index=False)
print(f"已成功将女性客户样本导出到 Excel 文件：{output_excel}")
print(f"导出记录总数：{len(female_df)} 行，字段数：{female_df.shape[1]} 列")

已成功将女性客户样本导出到 Excel 文件：女性客户样本.xlsx
导出记录总数：400 行，字段数：12 列