In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_table('..\\orders.txt', sep=',')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19490 entries, 0 to 19489
Data columns (total 25 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      19490 non-null  object
 1   order_date    19490 non-null  object
 2   store_name    19490 non-null  object
 3   pay_method    19490 non-null  object
 4   deliver_date  19490 non-null  object
 5   landed_days   19490 non-null  int64
 6   planned_days  19490 non-null  int64
 7   cust_id       19490 non-null  object
 8   cust_name     19490 non-null  object
 9   cust_type     19490 non-null  object
 10  city          19490 non-null  object
 11  province      19490 non-null  object
 12  region        19490 non-null  object
 13  product_id    19490 non-null  object
 14  product       19490 non-null  object
 15  category      19490 non-null  object
 16  subcategory   19490 non-null  object
 17  sales         19490 non-null  float64
 18  amount        19490 non-null  int64
 19  discount      19490 non-null  float64
 20  profit        19490 non-null  float64
 21  manager       19490 non-null  object
 22  return        19490 non-null  int64
 23  satisfied     19490 non-null  int64
 24  dt            19490 non-null  int64
dtypes: float64(3), int64(6), object(16)
memory usage: 3.7+ MB

In [3]:
df.head()

,order_id,order_date,store_name,pay_method,deliver_date,landed_days,planned_days,cust_id,cust_name,cust_type,...,category,subcategory,sales,amount,discount,profit,manager,return,satisfied,dt
0,CN-2014-100007,2014/1/1,定远店,信用卡,2014/1/6,5,6,Cust-11980,林丹,消费者,...,办公用品,系固件,1622.600,5,0.0,291.34,郝杰,1,0,2014
1,CN-2014-100001,2014/1/1,人民店,其它,2014/1/3,2,0,Cust-12430,苏冬露,小型企业,...,办公用品,收纳具,919.100,5,0.0,144.24,郝杰,0,0,2014
2,CN-2014-100002,2014/1/1,杨店店,支付宝,2014/1/3,2,2,Cust-12430,苏冬露,小型企业,...,办公用品,收纳具,284.480,4,0.0,47.53,郝杰,0,1,2014
3,CN-2014-100003,2014/1/1,庐江店,微信,2014/1/3,2,2,Cust-12430,苏冬露,小型企业,...,办公用品,信封,920.976,4,0.4,-41.49,郝杰,0,0,2014
4,CN-2014-100004,2014/1/1,金寨店,信用卡,2014/1/3,2,2,Cust-13405,薛光,消费者,...,办公用品,纸张,95.088,2,0.4,-8.05,张怡莲,0,0,2014

In [4]:
# 查看数据的描述性统计信息，包括计数、均值、标准差、最小、最大、四分位数等
df.describe()

,landed_days,planned_days,sales,amount,discount,profit,return,satisfied,dt
count,19490.000000,19490.000000,19490.000000,19490.000000,19490.000000,19490.000000,19490.000000,19490.000000,19490.000000
mean,3.977373,3.889790,1619.705539,3.771011,0.106303,96.047790,0.023858,0.023756,2016.920113
std,1.723409,1.924525,2637.578789,2.246256,0.187483,122.410091,0.152612,0.152291,1.883391
min,0.000000,0.000000,13.440000,1.000000,0.000000,-99.950000,0.000000,0.000000,2014.000000
25%,3.000000,2.000000,252.000000,2.000000,0.000000,12.210000,0.000000,0.000000,2015.000000
50%,4.000000,4.000000,636.510000,3.000000,0.000000,43.120000,0.000000,0.000000,2017.000000
75%,5.000000,6.000000,1793.883000,5.000000,0.200000,169.625000,0.000000,0.000000,2019.000000
max,7.000000,9.000000,35621.355000,14.000000,0.800000,499.880000,1.000000,1.000000,2020.000000

In [5]:
# 查看行数，等价于len(df)
df.shape[0]

19490

In [6]:
# 查看列数
df.shape[1]

25

In [7]:
#查看行索引
print(df.index)

RangeIndex(start=0, stop=19490, step=1)

In [8]:
#查看Dataframe的列索引
print(df.columns) # 返回索引对象
print(df.columns.values) # 返回列表

Index(['order_id', 'order_date', 'store_name', 'pay_method', 'deliver_date',
       'landed_days', 'planned_days', 'cust_id', 'cust_name', 'cust_type',
       'city', 'province', 'region', 'product_id', 'product', 'category',
       'subcategory', 'sales', 'amount', 'discount', 'profit', 'manager',
       'return', 'satisfied', 'dt'],
      dtype='object')
['order_id' 'order_date' 'store_name' 'pay_method' 'deliver_date'
 'landed_days' 'planned_days' 'cust_id' 'cust_name' 'cust_type' 'city'
 'province' 'region' 'product_id' 'product' 'category' 'subcategory'
 'sales' 'amount' 'discount' 'profit' 'manager' 'return' 'satisfied' 'dt']

### DataFrame数据选取

####  `loc[]`：基于行索引和列索引(标签)的方法选择数据

In [7]:
df.loc[:,'order_id'] #（1）选择指定标签对应的列
type(df.loc[:,'order_id']) #取出的数据是一维数据

pandas.core.series.Series

In [8]:
df.loc[:,['order_id']] #（2）选择指定标签对应的列
type(df.loc[:,['order_id']]) #取出的数据是二维表格

pandas.core.frame.DataFrame

In [9]:
df.loc[:,['order_id', 'order_date']] #选取多列数据

             order_id order_date
0      CN-2014-100007   2014/1/1
1      CN-2014-100001   2014/1/1
2      CN-2014-100002   2014/1/1
3      CN-2014-100003   2014/1/1
4      CN-2014-100004   2014/1/1
...               ...        ...
19485  CN-2020-101502  2020/6/30
19486  CN-2020-101503  2020/6/30
19487  CN-2020-101499  2020/6/30
19488  CN-2020-101500  2020/6/30
19489  CN-2020-101505  2020/6/30

[19490 rows x 2 columns]

#### `iloc[]`: 基于行和列的下标位置选择数据

In [10]:
df.iloc[0] # 选择第一行，等价于df.iloc[0,:]，得到的是Series

order_id               CN-2014-100007
order_date                   2014/1/1
store_name                        定远店
pay_method                        信用卡
deliver_date                 2014/1/6
landed_days                         5
planned_days                        6
cust_id                    Cust-11980
cust_name                          林丹
cust_type                         消费者
city                               沈阳
province                           辽宁
region                             东北
product_id              Prod-10003020
product         Stockwell_订书钉_每包_12_个
category                         办公用品
subcategory                       系固件
sales                          1622.6
amount                              5
discount                          0.0
profit                         291.34
manager                            郝杰
return                              1
satisfied                           0
dt                               2014
Name: 0, dtype: object

In [11]:
df.iloc[[0]] # 选择第一行，得到的是DataFrame

,order_id,order_date,store_name,pay_method,deliver_date,landed_days,planned_days,cust_id,cust_name,cust_type,...,category,subcategory,sales,amount,discount,profit,manager,return,satisfied,dt
0,CN-2014-100007,2014/1/1,定远店,信用卡,2014/1/6,5,6,Cust-11980,林丹,消费者,...,办公用品,系固件,1622.6,5,0.0,291.34,郝杰,1,0,2014

In [12]:
df.iloc[1:,] # 选择从第二行开始的全部数据

,order_id,order_date,store_name,pay_method,deliver_date,landed_days,planned_days,cust_id,cust_name,cust_type,...,category,subcategory,sales,amount,discount,profit,manager,return,satisfied,dt
1,CN-2014-100001,2014/1/1,人民店,其它,2014/1/3,2,0,Cust-12430,苏冬露,小型企业,...,办公用品,收纳具,919.100,5,0.0,144.24,郝杰,0,0,2014
2,CN-2014-100002,2014/1/1,杨店店,支付宝,2014/1/3,2,2,Cust-12430,苏冬露,小型企业,...,办公用品,收纳具,284.480,4,0.0,47.53,郝杰,0,1,2014
3,CN-2014-100003,2014/1/1,庐江店,微信,2014/1/3,2,2,Cust-12430,苏冬露,小型企业,...,办公用品,信封,920.976,4,0.4,-41.49,郝杰,0,0,2014
4,CN-2014-100004,2014/1/1,金寨店,信用卡,2014/1/3,2,2,Cust-13405,薛光,消费者,...,办公用品,纸张,95.088,2,0.4,-8.05,张怡莲,0,0,2014
5,CN-2014-103155,2014/1/1,众兴店,其它,2014/1/4,3,3,Cust-15190,谢君,消费者,...,家具,用具,1460.900,5,0.0,207.27,杨洪光,0,0,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19485,CN-2020-101502,2020/6/30,金寨店,微信,2020/7/2,2,1,Cust-18715,邢宁,公司,...,办公用品,用品,586.152,6,0.4,-41.40,王倩倩,0,1,2020
19486,CN-2020-101503,2020/6/30,海恒店,其它,2020/7/4,4,4,Cust-18715,邢宁,公司,...,办公用品,用品,2154.600,10,0.0,133.44,王倩倩,1,0,2020
19487,CN-2020-101499,2020/6/30,临泉店,其它,2020/7/2,2,3,Cust-19900,谭珊,消费者,...,办公用品,用品,108.080,2,0.0,47.99,杨洪光,0,0,2020
19488,CN-2020-101500,2020/6/30,海恒店,信用卡,2020/7/2,2,3,Cust-19900,谭珊,消费者,...,家具,书架,1700.160,1,0.0,194.63,王倩倩,0,0,2020
19489,CN-2020-101505,2020/6/30,定远店,微信,2020/7/4,4,4,Cust-21790,彭雯,消费者,...,技术,复印机,2034.900,3,0.0,149.44,杨洪光,1,0,2020

In [13]:
df.iloc[:,[0]] # 选择第一列数据

             order_id
0      CN-2014-100007
1      CN-2014-100001
2      CN-2014-100002
3      CN-2014-100003
4      CN-2014-100004
...               ...
19485  CN-2020-101502
19486  CN-2020-101503
19487  CN-2020-101499
19488  CN-2020-101500
19489  CN-2020-101505

[19490 rows x 1 columns]

In [14]:
df.iloc[:,[0,1]] # 选择前两列数据

             order_id order_date
0      CN-2014-100007   2014/1/1
1      CN-2014-100001   2014/1/1
2      CN-2014-100002   2014/1/1
3      CN-2014-100003   2014/1/1
4      CN-2014-100004   2014/1/1
...               ...        ...
19485  CN-2020-101502  2020/6/30
19486  CN-2020-101503  2020/6/30
19487  CN-2020-101499  2020/6/30
19488  CN-2020-101500  2020/6/30
19489  CN-2020-101505  2020/6/30

[19490 rows x 2 columns]

In [15]:
df.iloc[0,0] # 基于行和列的位置选取特定数据

'CN-2014-100007'

In [16]:
#直接选取某列或若干列的数据
# df[['order_id']]
# df.order_id
df[['order_id','order_date']]

             order_id order_date
0      CN-2014-100007   2014/1/1
1      CN-2014-100001   2014/1/1
2      CN-2014-100002   2014/1/1
3      CN-2014-100003   2014/1/1
4      CN-2014-100004   2014/1/1
...               ...        ...
19485  CN-2020-101502  2020/6/30
19486  CN-2020-101503  2020/6/30
19487  CN-2020-101499  2020/6/30
19488  CN-2020-101500  2020/6/30
19489  CN-2020-101505  2020/6/30

[19490 rows x 2 columns]

In [17]:
#选取符合条件的数据
df[df.amount>10] # 等价于df.loc[df.amount>10]

,order_id,order_date,store_name,pay_method,deliver_date,landed_days,planned_days,cust_id,cust_name,cust_type,...,category,subcategory,sales,amount,discount,profit,manager,return,satisfied,dt
51,CN-2014-100073,2014/1/11,人民店,其它,2014/1/15,4,6,Cust-15415,戴康,消费者,...,家具,书架,1714.44,13,0.0,161.38,张怡莲,0,0,2014
68,CN-2014-100109,2014/1/15,临泉店,支付宝,2014/1/20,5,5,Cust-18130,袁梅,公司,...,办公用品,标签,3166.24,11,0.0,175.53,杨洪光,0,0,2014
97,CN-2014-100133,2014/1/20,众兴店,其它,2014/1/25,5,6,Cust-21580,曹伟,消费者,...,办公用品,器具,2368.80,12,0.0,250.12,郝杰,0,0,2014
150,CN-2014-100219,2014/2/4,临泉店,信用卡,2014/2/6,2,2,Cust-20095,郝升,消费者,...,办公用品,美术,2551.78,11,0.0,178.64,王倩倩,0,0,2014
244,CN-2014-100350,2014/2/22,众兴店,其它,2014/2/28,6,6,Cust-17875,涂珑,小型企业,...,家具,书架,2677.92,12,0.0,205.84,姜伟,0,0,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18947,CN-2020-100968,2020/5/12,临泉店,微信,2020/5/15,3,3,Cust-18070,钱幂,小型企业,...,办公用品,收纳具,6885.34,11,0.0,363.82,杨洪光,0,0,2020
19077,CN-2020-101097,2020/5/23,临泉店,信用卡,2020/5/27,4,4,Cust-17950,方蔓楚,消费者,...,技术,电话,11513.04,14,0.0,333.78,张怡莲,0,0,2020
19082,CN-2020-101107,2020/5/24,金寨店,微信,2020/5/31,7,6,Cust-13210,程根基,消费者,...,办公用品,收纳具,3481.66,13,0.0,101.34,郝杰,0,0,2020
19324,CN-2020-101354,2020/6/18,燎原店,信用卡,2020/6/21,3,3,Cust-10330,廖保,消费者,...,办公用品,信封,2828.28,13,0.0,210.09,杨洪光,0,0,2020
19425,CN-2020-101433,2020/6/24,海恒店,信用卡,2020/6/28,4,4,Cust-21190,黄涛,小型企业,...,办公用品,标签,608.30,11,0.0,175.73,姜伟,0,0,2020

#### DataFrame的操作与计算

In [18]:
df['discount'].corr(df['profit']) #计算两列的相关性

-0.4180852633038127

In [19]:
df.groupby('store_name')[['sales','profit']].sum() #分组求和

                  sales     profit
store_name
临泉店         3774225.952  221276.86
人民店         3329926.558  201987.60
众兴店         3791267.165  225528.25
定远店         3445234.352  212202.94
庐江店         3505012.553  214328.09
杨店店         3344368.597  201630.02
海恒店         3625606.292  202625.56
燎原店         3314062.654  193641.39
金寨店         3438356.838  198750.72

In [20]:
df.sort_values(by='order_date', ascending=False, inplace=False) #根据某列的值进行排序

,order_id,order_date,store_name,pay_method,deliver_date,landed_days,planned_days,cust_id,cust_name,cust_type,...,category,subcategory,sales,amount,discount,profit,manager,return,satisfied,dt
19240,CN-2020-101257,2020/6/9,杨店店,其它,2020/6/12,3,1,Cust-21070,薛婷,消费者,...,家具,书架,3476.20,5,0.0,194.36,郝杰,0,0,2020
19235,CN-2020-101256,2020/6/9,杨店店,微信,2020/6/12,3,3,Cust-10285,涂安,公司,...,办公用品,纸张,612.50,5,0.0,115.57,杨洪光,0,0,2020
19232,CN-2020-101253,2020/6/9,海恒店,其它,2020/6/10,1,1,Cust-10285,涂安,公司,...,办公用品,美术,1590.96,6,0.0,123.56,张怡莲,1,0,2020
19233,CN-2020-101254,2020/6/9,临泉店,微信,2020/6/10,1,1,Cust-10285,涂安,公司,...,办公用品,器具,15093.12,6,0.0,499.73,张怡莲,0,0,2020
19234,CN-2020-101255,2020/6/9,人民店,信用卡,2020/6/12,3,3,Cust-10285,涂安,公司,...,办公用品,标签,267.40,5,0.0,25.81,杨洪光,0,0,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,CN-2014-100001,2014/1/1,人民店,其它,2014/1/3,2,0,Cust-12430,苏冬露,小型企业,...,办公用品,收纳具,919.10,5,0.0,144.24,郝杰,0,0,2014
5,CN-2014-103155,2014/1/1,众兴店,其它,2014/1/4,3,3,Cust-15190,谢君,消费者,...,家具,用具,1460.90,5,0.0,207.27,杨洪光,0,0,2014
6,CN-2014-103146,2014/1/1,金寨店,支付宝,2014/1/4,3,3,Cust-15655,徐关茵,公司,...,办公用品,收纳具,969.92,4,0.0,118.42,王倩倩,0,0,2014
7,CN-2014-100005,2014/1/1,众兴店,信用卡,2014/1/3,2,2,Cust-20785,袁松,消费者,...,办公用品,纸张,874.44,6,0.0,188.61,张怡莲,0,0,2014
0,CN-2014-100007,2014/1/1,定远店,信用卡,2014/1/6,5,6,Cust-11980,林丹,消费者,...,办公用品,系固件,1622.60,5,0.0,291.34,郝杰,1,0,2014

In [21]:
df['product'].value_counts() #计算product列中每个值出现的次数

product
Stockwell_图钉_每包_12_个    34
Fiskars_尺子_蓝色           30
Stockwell_夹子_混合尺寸       30
GlobeWeis_外皮和封条_回收      29
Avery_订书机_回收            28
                        ..
Barricks_会议桌_组装          1
Hon_木桌_黑色                1
SanDisk_羊皮纸_回收           1
Lesro_咖啡桌_黑色             1
SanDisk_令_每包_12_个        1
Name: count, Length: 1953, dtype: int64

In [22]:
df['product'].unique() #列出product列中的所有可能取值

array(['Stockwell_订书钉_每包_12_个', 'Rogers_文件夹_单宽度', 'Tenex_盘_工业', ...,
       'Lesro_咖啡桌_黑色', 'Eldon_文件夹_蓝色', 'SanDisk_令_每包_12_个'], dtype=object)

In [23]:
df[df['product'].str.contains('Stockwell_图钉_每包_12_个')] #在product列查找"Stockwell_图钉_每包12_个"商品的售卖信息

,order_id,order_date,store_name,pay_method,deliver_date,landed_days,planned_days,cust_id,cust_name,cust_type,...,category,subcategory,sales,amount,discount,profit,manager,return,satisfied,dt
356,CN-2014-100484,2014/3/11,燎原店,微信,2014/3/14,3,1,Cust-18430,唐木兰,消费者,...,办公用品,系固件,1156.260,3,0.0,140.21,王倩倩,0,1,2014
1205,CN-2014-101616,2014/7/18,燎原店,其它,2014/7/22,4,3,Cust-13375,夏光,消费者,...,办公用品,系固件,136.584,3,0.4,40.75,王倩倩,0,0,2014
1226,CN-2014-101640,2014/7/22,临泉店,微信,2014/7/23,1,1,Cust-20860,钟宣,公司,...,办公用品,系固件,3569.160,2,0.4,198.82,杨洪光,0,0,2014
1953,CN-2014-102633,2014/10/14,庐江店,其它,2014/10/19,5,6,Cust-20995,白斯云,消费者,...,办公用品,系固件,189.000,5,0.4,-12.60,郝杰,0,0,2014
2113,CN-2014-102827,2014/10/29,定远店,微信,2014/11/3,5,6,Cust-19885,孟珊,公司,...,办公用品,系固件,150.360,2,0.0,16.76,杨洪光,0,0,2014
2707,CN-2015-103124,2015/1/1,定远店,微信,2015/1/3,2,2,Cust-18835,孙谙,公司,...,办公用品,系固件,1357.440,6,0.0,181.71,王倩倩,0,0,2015
3586,CN-2015-101003,2015/6/10,杨店店,其它,2015/6/15,5,6,Cust-16540,余丽娜,消费者,...,办公用品,系固件,2775.360,7,0.0,261.09,杨洪光,0,0,2015
3966,CN-2015-101423,2015/8/5,海恒店,信用卡,2015/8/7,2,2,Cust-21790,彭雯,消费者,...,办公用品,系固件,81.060,3,0.8,-0.67,郝杰,1,0,2015
4664,CN-2015-102210,2015/10/11,燎原店,信用卡,2015/10/17,6,8,Cust-16810,刘立,消费者,...,办公用品,系固件,529.760,4,0.0,56.78,姜伟,0,0,2015
5202,CN-2015-102824,2015/11/30,海恒店,微信,2015/12/5,5,6,Cust-15520,肖崆,消费者,...,办公用品,系固件,1227.100,5,0.0,233.57,姜伟,0,0,2015
5933,CN-2016-100503,2016/4/5,杨店店,其它,2016/4/9,4,6,Cust-11785,邓达侠,消费者,...,办公用品,系固件,2460.920,2,0.0,230.88,郝杰,0,0,2016
6257,CN-2016-100815,2016/5/24,海恒店,其它,2016/5/25,1,1,Cust-16225,毛丽美,公司,...,办公用品,系固件,94.080,2,0.0,11.91,杨洪光,0,0,2016
6343,CN-2016-100931,2016/6/1,庐江店,信用卡,2016/6/6,5,6,Cust-13030,殷凤,小型企业,...,办公用品,系固件,1267.392,8,0.4,-67.70,王倩倩,0,0,2016
7193,CN-2016-101795,2016/9/10,燎原店,微信,2016/9/15,5,5,Cust-17155,施良,消费者,...,办公用品,系固件,222.040,2,0.0,40.53,姜伟,0,0,2016
7199,CN-2016-101794,2016/9/10,海恒店,支付宝,2016/9/15,5,6,Cust-19960,许绅,消费者,...,办公用品,系固件,539.840,2,0.0,111.67,郝杰,0,0,2016
8788,CN-2017-100481,2017/4/1,临泉店,微信,2017/4/5,4,4,Cust-11785,邓达侠,消费者,...,办公用品,系固件,117.320,2,0.0,35.49,郝杰,0,0,2017
9082,CN-2017-100776,2017/5/19,燎原店,其它,2017/5/23,4,6,Cust-16225,毛丽美,公司,...,办公用品,系固件,58.660,1,0.0,13.06,杨洪光,0,0,2017
9211,CN-2017-100907,2017/5/31,庐江店,信用卡,2017/6/4,4,4,Cust-13030,殷凤,小型企业,...,办公用品,系固件,293.300,5,0.0,15.42,王倩倩,0,0,2017
10143,CN-2017-101836,2017/9/13,海恒店,信用卡,2017/9/14,1,1,Cust-19960,许绅,消费者,...,办公用品,系固件,351.960,10,0.4,34.27,江奕健,0,0,2017
10153,CN-2017-101839,2017/9/14,临泉店,其它,2017/9/14,0,0,Cust-17155,施良,消费者,...,办公用品,系固件,58.660,1,0.0,7.42,杨洪光,0,0,2017
12238,CN-2018-100990,2018/6/10,庐江店,其它,2018/6/13,3,3,Cust-16540,余丽娜,消费者,...,办公用品,系固件,175.980,3,0.0,11.64,王倩倩,0,0,2018
12663,CN-2018-101408,2018/8/3,杨店店,支付宝,2018/8/4,1,1,Cust-21790,彭雯,消费者,...,办公用品,系固件,527.940,9,0.0,84.65,郝杰,0,0,2018
13468,CN-2018-102221,2018/10/12,海恒店,其它,2018/10/16,4,4,Cust-16810,刘立,消费者,...,办公用品,系固件,351.960,6,0.0,27.51,张怡莲,0,0,2018
14065,CN-2018-102821,2018/11/30,人民店,其它,2018/12/4,4,4,Cust-15520,肖崆,消费者,...,办公用品,系固件,70.392,2,0.4,17.78,张怡莲,0,0,2018
14857,CN-2019-100494,2019/3/12,定远店,支付宝,2019/3/12,0,0,Cust-18430,唐木兰,消费者,...,办公用品,系固件,302.400,5,0.0,12.77,杨洪光,0,0,2019
15068,CN-2019-100708,2019/4/11,杨店店,信用卡,2019/4/13,2,1,Cust-10030,贾嫒,公司,...,办公用品,系固件,120.960,2,0.0,11.14,郝杰,0,0,2019
15959,CN-2019-101600,2019/7/15,人民店,信用卡,2019/7/18,3,1,Cust-13375,夏光,消费者,...,办公用品,系固件,241.920,4,0.0,24.16,王倩倩,0,0,2019
15973,CN-2019-101610,2019/7/17,人民店,信用卡,2019/7/19,2,1,Cust-20860,钟宣,公司,...,办公用品,系固件,70.392,2,0.4,10.35,杨洪光,0,0,2019
16971,CN-2019-102610,2019/10/13,众兴店,其它,2019/10/18,5,5,Cust-20995,白斯云,消费者,...,办公用品,系固件,181.440,3,0.0,21.42,王倩倩,0,0,2019
17147,CN-2019-102787,2019/10/26,杨店店,信用卡,2019/11/1,6,6,Cust-19885,孟珊,公司,...,办公用品,系固件,181.440,3,0.0,36.82,姜伟,0,0,2019
17160,CN-2019-102798,2019/10/27,杨店店,其它,2019/11/1,5,5,Cust-21190,黄涛,小型企业,...,办公用品,系固件,351.960,6,0.0,32.21,王倩倩,0,0,2019
17806,CN-2019-103430,2019/12/18,定远店,微信,2019/12/22,4,4,Cust-20980,孟斯云,公司,...,办公用品,系固件,108.864,3,0.4,42.52,王倩倩,0,0,2019
18454,CN-2020-100469,2020/3/10,庐江店,其它,2020/3/15,5,5,Cust-20785,袁松,消费者,...,办公用品,系固件,302.400,5,0.0,12.77,杨洪光,0,0,2020
18670,CN-2020-100683,2020/4/8,海恒店,信用卡,2020/4/11,3,1,Cust-20500,邓姝,消费者,...,办公用品,系固件,120.960,2,0.0,11.14,郝杰,0,0,2020

In [24]:
# dataframe的连接
# 以字典的形式定义df1
df1 = pd.DataFrame({'alpha':['A','B','B','C','D','E'],'feature1':[1,1,2,3,3,1],
            'feature2':['low','medium','medium','high','low','high']})

df1.head()

  alpha  feature1 feature2
0     A         1      low
1     B         1   medium
2     B         2   medium
3     C         3     high
4     D         3      low

In [25]:
# 定义df2
df2 = pd.DataFrame({'alpha':['A','A','B','F'],'pazham':['apple','orange','pine','pear'],
            'kilo':['high','low','high','medium'],'price':np.array([5,6,5,7])})
df2.head()

  alpha  pazham    kilo  price
0     A   apple    high      5
1     A  orange     low      6
2     B    pine    high      5
3     F    pear  medium      7

In [26]:
df3 = pd.concat([df1,df2], axis=1) #按列拼接
df3

  alpha  feature1 feature2 alpha  pazham    kilo  price
0     A         1      low     A   apple    high    5.0
1     B         1   medium     A  orange     low    6.0
2     B         2   medium     B    pine    high    5.0
3     C         3     high     F    pear  medium    7.0
4     D         3      low   NaN     NaN     NaN    NaN
5     E         1     high   NaN     NaN     NaN    NaN

In [27]:
# 删除缺失值
# df3.isna()
df3.dropna()

  alpha  feature1 feature2 alpha  pazham    kilo  price
0     A         1      low     A   apple    high    5.0
1     B         1   medium     A  orange     low    6.0
2     B         2   medium     B    pine    high    5.0
3     C         3     high     F    pear  medium    7.0

In [28]:
pd.concat([df1,df2], axis=0) #按行拼接

  alpha  feature1 feature2  pazham    kilo  price
0     A       1.0      low     NaN     NaN    NaN
1     B       1.0   medium     NaN     NaN    NaN
2     B       2.0   medium     NaN     NaN    NaN
3     C       3.0     high     NaN     NaN    NaN
4     D       3.0      low     NaN     NaN    NaN
5     E       1.0     high     NaN     NaN    NaN
0     A       NaN      NaN   apple    high    5.0
1     A       NaN      NaN  orange     low    6.0
2     B       NaN      NaN    pine    high    5.0
3     F       NaN      NaN    pear  medium    7.0

In [29]:
df1.merge(df2,how='inner',on='alpha') # 基于共同列alpha的内连接

  alpha  feature1 feature2  pazham  kilo  price
0     A         1      low   apple  high      5
1     A         1      low  orange   low      6
2     B         1   medium    pine  high      5
3     B         2   medium    pine  high      5

In [30]:
df1.merge(df2,how='outer',on='alpha') # 基于共同列的并集进行外连接

  alpha  feature1 feature2  pazham    kilo  price
0     A       1.0      low   apple    high    5.0
1     A       1.0      low  orange     low    6.0
2     B       1.0   medium    pine    high    5.0
3     B       2.0   medium    pine    high    5.0
4     C       3.0     high     NaN     NaN    NaN
5     D       3.0      low     NaN     NaN    NaN
6     E       1.0     high     NaN     NaN    NaN
7     F       NaN      NaN    pear  medium    7.0

In [31]:
df1.merge(df2,how='left',on='alpha') # 基于共同列alpha的左连接

  alpha  feature1 feature2  pazham  kilo  price
0     A         1      low   apple  high    5.0
1     A         1      low  orange   low    6.0
2     B         1   medium    pine  high    5.0
3     B         2   medium    pine  high    5.0
4     C         3     high     NaN   NaN    NaN
5     D         3      low     NaN   NaN    NaN
6     E         1     high     NaN   NaN    NaN

In [32]:
df1.merge(df2,how='right',on='alpha')# 基于共同列alpha的右连接

  alpha  feature1 feature2  pazham    kilo  price
0     A       1.0      low   apple    high      5
1     A       1.0      low  orange     low      6
2     B       1.0   medium    pine    high      5
3     B       2.0   medium    pine    high      5
4     F       NaN      NaN    pear  medium      7

In [33]:
#更改列名
df.rename(columns={'order_id':'订单号'}, inplace=True) #更改某一个列的列名

In [34]:
# 导出到文件
df.to_excel('orders_data.xlsx', sheet_name='data', index=False)